### ISSUE TITLE
Failed to install helmreleases CRD

### ISSUE THREAD

**Issue by paulcarlton-ww** [fluxcd/toolkit#112]
I am trying to install gitops toolkit on a brand new Kind cluster and get error relating to "x-kubernetes-preserve-unknown-fields

tk check --pre
► checking prerequisites
✔ kubectl 1.18.3 >=1.18.0
✔ Kubernetes 1.14.2 >=1.14.0
✔ prerequisites checks passed
a669981@vc2crtp2473106n:~$ tk install --export > gitops.yaml
a669981@vc2crtp2473106n:~$ kubectl apply -f gitops.yaml
namespace/gitops-system created
customresourcedefinition.apiextensions.k8s.io/alerts.notification.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/gitrepositories.source.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/helmcharts.source.fluxcd.io configured
error: error validating "gitops.yaml": error validating data: ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.values): unknown field "x-kubernetes-preserve-unknown-fields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by stefanprodan** [comment]
We are dropping support for Kubernetes <1.16 see #111
