### ISSUE TITLE
DependsOn doesn't check observedGeneration

### ISSUE THREAD

**Issue by seaneagan** [fluxcd/toolkit#125]
Currently when checking HelmReleases and Kustomizations specified in DependsOn, the Ready condition is checked, but not that `status.observedGeneration` matches the latests `metadata.generation`. So those resources may not have been reconciled with the latest state yet, which they probably should be. I suppose there could still be race conditions where a controller sees an updated resource before all depended on resources have been updated, but that seems less likely.

**Comment by hiddeco** [comment]
Thank you for the suggestion @seaneagan :tulip:
