### ISSUE TITLE
Error using tk completion command on zshrc

### ISSUE THREAD

**Issue by mmorejon** [fluxcd/toolkit#129]
Hi!
I'm following the [Getting Started](https://toolkit.fluxcd.io/get-started/#install-the-toolkit-cli) steps and I getting the following error:
```
. <(tk completion)
/dev/fd/11:type:1874: bad option: -t
```
If I run `tk completion` alone then works perfect, but if I try to include it into my `~/.zshrc` file I receive the error mentioned above.

Environment:
* darwin
* zsh
* tk version 0.0.11

**Comment by stefanprodan** [comment]
As mentioned in the docs, the completion works for bash only.

**Comment by hiddeco** [comment]
Cobra does offer utilities to generate ZSH completion, so we may want to create a new issue out of this to extend the support to other shell types.

**Comment by mmorejon** [comment]
> Cobra does offer utilities to generate ZSH completion, so we may want to create a new issue out of this to extend the support to other shell types.

Will be really nice!

**Comment by mmorejon** [comment]
> As mentioned in the docs, the completion works for bash only.

Thank you! I have skipped that detail
