### ISSUE TITLE
Beautify roadmap md

### ISSUE THREAD

**Issue by bia** [fluxcd/toolkit#132]
@dholbach and I plan to add a [progress bar](https://facelessuser.github.io/pymdown-extensions/extensions/progressbar/) and change the bullets to checkmarks. Checked/finished items will be in grey.

**Comment by dholbach** [comment]
Looks like progressbars can't easily be done: https://github.com/squidfunk/mkdocs-material/issues/862 - AFAIUI we'd need to turn https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/extensions/_progressbar.scss into CSS for this to work? :shrug:
