### ISSUE TITLE
Change CRD domains to `*.toolkit.fluxcd.io`

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/toolkit#136]
The main reason for this is to be able to offer a migration path to Helm Operator in which the Helm Operator and helm-controller can be run in parallel on the same cluster. Due to Kubernetes' assumptions around Custom Resource Definitions, this is not possible without either:

1) introducing a new `Kind` for the current `helm.fluxcd.io` domain
2) changing the domain so that the CRD from the Helm Operator and the helm-controller do not collide

Given that `HelmRelease` has proven to be the right name for the `Kind`, we have opted for option 2. And given all controllers are part of the Toolkit, it makes most sense to change the domains for all of them to not create any confusion.

Toolkit projects that require changes:

- [x] source-controller
- [x] helm-controller
- [x] kustomize-controller
- [x] notification-controller
- [x] toolkit

**Comment by stefanprodan** [comment]
Those PRs will break the controllers if we don't update the dependent API packages. We need to merge/release source-controller, then update the pkg in kustomize/helm, then merge/release both, then update source/kustomize apis in notification. After we release notification only then we can update the toolkit and pull all the API packages.

**Comment by stefanprodan** [comment]
This fixes #110
