### ISSUE TITLE
bootstrap branch into a flag

### ISSUE THREAD

**Issue by hhollenstain** [fluxcd/toolkit#169]
When bootstrapping a cluster it is hardcoded const to `master`. Hoping this would be updated to default to main and we can make this a flag. 

https://github.com/fluxcd/toolkit/blob/master/cmd/tk/bootstrap.go#L42

**Comment by stefanprodan** [comment]
We've reached out to GitHub regarding this, the repository create API doesn't allow specifying a branch name right now but it will change in the future. We have added a default branch option to the [go-git-providers](https://github.com/fluxcd/go-git-providers/blob/master/gitprovider/types_repository.go#L49-L54) and we'll expose it as a command arg when it's supported.

**Comment by shanesveller** [comment]
As a seemingly-small variation, I have a pre-existing repo that was previously `tk bootstrap` 'd that now uses something other than `master` as the primary development branch, but when I bootstrap a new cluster into the same repo it attempts to commit to `master` and push, which in my case was denied by branch protections.
