### ISSUE TITLE
`tk` binary conflicts with Tanka

### ISSUE THREAD

**Issue by Duologic** [fluxcd/toolkit#174]
The toolkit binary `tk` conflicts with the binary from Tanka (https://tanka.dev/), which is unfortunately operating in the same area and might cause trouble for quite a bit of Kubernetes users.

**Comment by hiddeco** [comment]
Thank you for bringing this to our attention. :sunflower: 

Two alternatives come to mind: `gotk` (short for GitOps Toolkit), or `gitops` which would result in some nice looking commands (i.e. `gitops bootstrap`).

cc/ @squaremo @stefanprodan

**Comment by Duologic** [comment]
I'd find `gitops` a bit more confusing as the concept != command. (great job on the tool/docs, will try it out soon)

**Comment by squaremo** [comment]
I like `gotk`.
