### ISSUE TITLE
Move HelmRelease to helm.toolkit.fluxcd.io/v1(alpha1) ?

### ISSUE THREAD

**Issue by seaneagan** [fluxcd/toolkit#181]
Since HelmRelease moved to a new api version domain (helm.toolkit.fluxcd.io) with #136, should it be v1alpha1 instead of v2alpha1, since this is technically the first version of this CRD, (as identified by the toolkit domain)? Currently it could be confused that this is the second version within the toolkit. I can see both sides, just making sure it was considered.

**Comment by seaneagan** [comment]
It also aligns with HelmRepository/HelmChart being v1. Most of the data they contain was originally part of HelmRelease v1. If #233 is accepted, this would seem to bolster the case for this further.

cc @hiddeco @stefanprodan

**Comment by stefanprodan** [comment]
I'm for keeping v2alpha1 and source-controller as it is. We moved the HelmRelease to the toolkit subdomain to allow users to run both helm-op and and helm-controller in parallel while they migrate from v1 to v2.

**Comment by hiddeco** [comment]
We have historically had a domain change in the past (from `flux.weave.works/v1beta1` -> `helm.fluxcd.io/v1`), and this was easy to grasp for people migrating (as they are aware of the project's history), while not being confusing to new users.

**Comment by seaneagan** [comment]
Sounds good, one's expectations probably vary depending on if they're a new or old user, so no perfect answer, and keeping it as is less work.
