### ISSUE TITLE
Bootstrapping clusters to the same path

### ISSUE THREAD

**Issue by hhollenstain** [fluxcd/toolkit#186]
# What is the problem?
Currently looking at managing multiple clusters with the same base line of daemonsets, ingress controllers, etc. I was trying to bootstrap them all to the same path. The issue I am running into is the deploy key is set as `tk-<path>` this will purge the last clusters deploy key. I was hoping we can potentially be able to change the name of the key so we can bootstrap multiple clusters on github to the same path.

**Comment by hhollenstain** [comment]
Been doing some more digging in how to set this up in multiple clusters even mirrored clusters. This maybe completely unnecessary. After doing some more bootstrapping and testing I will update any more thoughts on this.

**Comment by stefanprodan** [comment]
There a couple of options: you can create a dedicated repo with your cluster baseline or add the baseline to the fleet-repo as a kustomize base.

**Comment by hhollenstain** [comment]
@stefanprodan I actually did the second option you mentioned as a kustomize base and is working out well.
