### ISSUE TITLE
An issue with the gitops-system reconsiliation

### ISSUE THREAD

**Issue by moikot** [fluxcd/toolkit#206]
All the resources in gitops-system namespace are unexpectedly deleted when I add an additional YAML file into fleet-infra\staging-cluster\ created by the bootstrap process.

Steps to reproduce:
1. Deploy resources using the bootstrap `gotk bootstrap github --owner=$GITHUB_USER --repository=fleet-infra --path=staging-cluster --personal --arch=arm64`. I'm using --arch=arm64 but I don't think it should affect anything
3. Pull the created repository and add a resource description into fleet-infra\staging-cluster\, a namespace definition for example. I'm using 01-namespace.yml containing 

```YAML
apiVersion: v1
kind: Namespace
metadata:
  name: lens-metrics-2
```

So that the structure looks like this:

```
├── staging-cluster 
│   └── gitops-system 
│   │  ├── toolkit-components.yaml
│   │  ├── toolkit-kustomization.yaml
│   │  └── toolkit-source.yaml
│   └── lens-metrics-2
│       └── 01-namespace.yml 
```

4. Commit the changes and push.
5. Observe that pods and all other resources in gitops-system (apart of GitRepository and Kustomization definitions) are deleted and never come back again.

When I delete finalizers from the remaining GitRepository and Kustomization CRDs and they finally go away I'm able to execute the bootstrap command from step two and all the resources come back including the namespace I added at step 3.

**Comment by stefanprodan** [comment]
@moikot this was a bug in GC after the last refactoring, thanks for reporting it. You can run now `gotk bootstrap` and it will pull kustomize-controller v0.0.10 that has the fix for this.
