### ISSUE TITLE
Unable to deploy GitOps toolkit

### ISSUE THREAD

**Issue by mnaser** [fluxcd/toolkit#241]
I've just tried to deploy the GitOps toolkit using the existing tooling and it seems like the published GitHub registry images cannot be pulled:

```
❯ docker pull ghcr.io/fluxcd/notification-controller:v0.0.10
v0.0.10: Pulling from fluxcd/notification-controller
df20fa9351a1: Already exists 
207995d28a57: Pulling fs layer 
887ea3b292e5: Pulling fs layer 
224a3681e710: Pulling fs layer 
4076933fed24: Waiting 
error pulling image configuration: unknown blob
```

Inside Kubernetes, I'm seeing something like this:

```
Failed to pull image "ghcr.io/fluxcd/notification-controller:v0.0.10": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/fluxcd/notification-controller:v0.0.10": failed to copy: httpReaderSeeker: failed open: could not fetch content descriptor sha256:af37d5603969808bb7a44f9e8567024db9ddee736bd742c839cb88ff25c6eaca (application/vnd.docker.container.image.v1+json) from remote: not found
```

**Comment by hiddeco** [comment]
Retriggering the release build fixed the issue, seems that the GitHub Action creates a corrupt image once in awhile which needs to be addressed.

**Comment by stefanprodan** [comment]
Got the same problem with corrupted layers on Docker Hub, this is happened after we switched to Docker GitHub Action v2...

**Comment by mnaser** [comment]
`source-controller` is good to go, but all the others are still ImagePullBackOff.

```
❯ kubectl -n gitops-system get pods -owide
NAME                                      READY   STATUS             RESTARTS   AGE   IP               NODE    NOMINATED NODE   READINESS GATES
helm-controller-c6fd74947-8rw9s           0/1     ImagePullBackOff   0          21s   10.244.245.133   kvm8    <none>           <none>
kustomize-controller-7bdfbd4fb8-gwjz9     0/1     ImagePullBackOff   0          20s   10.244.32.197    kvm1    <none>           <none>
notification-controller-65c69bddc-2fg8c   0/1     ImagePullBackOff   0          20s   10.244.186.5     kvm6    <none>           <none>
source-controller-88b79fcd7-zmb29         1/1     Running            0          20s   10.244.150.133   kvm13   <none>           <none>
```

Is it still in the pipeline of being built or probably needs a rekick too?

**Comment by hiddeco** [comment]
> Got the same problem with corrupted layers on Docker Hub, this happened after we switched to Docker GitHub Action v2...

Commented on issue https://github.com/docker/build-push-action/issues/127#issuecomment-694286130

**Comment by crazy-max** [comment]
@stefanprodan Someone else got this issue with DockerHub (https://github.com/jrcichra/lancache-rpi/issues/12) so I don't think this is related to the action but buildx/buildkit itself.

**Comment by hiddeco** [comment]
A sanity check has been added to the release pipelines.
