### ISSUE TITLE
on bootstrap, toolkit-kustomization.yaml is not applied

### ISSUE THREAD

**Issue by yawboateng** [fluxcd/toolkit#255]
toolkit-kustomization.yaml file is committed to the git repo but its not automatically applied to the cluster, which in turn doesnt not sync any files I add to the git repo. I had to manually kubectl apply it to get the cluster in sync

**Comment by stefanprodan** [comment]
The bootstrap is run on each commit in e2e tests.  I've also tried it manually and I can't reproduce it, please supply the bootstrap logs.

**Comment by stefanprodan** [comment]
I've fund the issue, the kustomization apply was skipped if there was one in the repo, but the previous apply could fail so it should apply every time.
