### ISSUE TITLE
Security vulnerabilities during evaluation 

### ISSUE THREAD

**Issue by maheswarasunil** [fluxcd/toolkit#274]
We are looking for using the toolkit in our project. As part of that process, when we did a security scan there are few vulnerabilities reported. 

Report scan can be download from the below link
`https://github.com/maheswarasunil/toolkitreport/raw/master/Nexus_scan_report`

Is it possible to address these vulnerabilities?

**Comment by stefanprodan** [comment]
None of those CVEs are applicable to gotk, we don' use websockets nor ectd in CLI, these packages come from upstream .e.g. Kubernetes.
