### ISSUE TITLE
Support JSON manifest files

### ISSUE THREAD

**Issue by JanRK** [fluxcd/toolkit#275]
Stolen from https://github.com/fluxcd/flux/issues/2755

**Describe the bug**
When deciding what files to pass to kubectl, gotk ignores .json files in its target repository/branch/path.

**To Reproduce**
Set up a cluster with gotk. Add a valid namespace manifest file such as the one below to the target git repo/branch/path and name it *.json

```
{
  "apiVersion": "v1",
  "kind": "Namespace",
  "metadata": {
    "namespace": "test-namespace"
  }
}
```
**Expected behavior**
Gotk should pick up this file and apply it to the cluster under management.

**What actually happens**
Gotk notices that the git repo has changed, but does not apply the json file. Just renaming the json file to yaml does not work either.

**Additional notes**
.yaml, .yml and .json files are all accepted by kubectl, and gotk should mirror this behaviour.

**Comment by stefanprodan** [comment]
GOTK uses Kustomize for ordering, patching, labeling, etc. Kustomize only works with YAML files that's why we can't support JSON.
