### ISSUE TITLE
Output tables for `gotk get` commands

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/toolkit#292]
The current `gotk get` commands write simple lines to `stdout`.Which is not very readable, and does not provide a great overview of the status the resources are in.

Instead, we should write the output to tables which (at least) should include:

* Name
* Current revision
* Ready status (`True`, `False`, `Unknown`)
* Ready message

**Comment by stefanprodan** [comment]
It would be great to add `--all-namespaces` to the get commands, the table output should contain a namespace column when this flag is present.
