### ISSUE TITLE
Add ARM note in get-started documentation

### ISSUE THREAD

**Issue by blmhemu** [fluxcd/toolkit#306]
I think this is an error with :
Node-Selectors:  kubernetes.io/arch=amd64
                 kubernetes.io/os=linux

I think we need to include arch=arm

![image](https://user-images.githubusercontent.com/19410501/95097803-8594df80-074b-11eb-9fd7-04b83a96667f.png)

**Comment by hiddeco** [comment]
See the "ARM" note in the installation guide: https://toolkit.fluxcd.io/guides/installation/#bootstrap

**Comment by blmhemu** [comment]
Hey ! Truly sorry for this. Should have read the docs better. But thanks for the quick help.

**Comment by blmhemu** [comment]
Hey ! Can you please add the same Note under getting started page (https://toolkit.fluxcd.io/get-started/) ?

**Comment by nanikjava** [comment]
@hiddeco is this how the get-started documentation should look like after adding the ARM section from installation doc ?

![Screenshot from 2020-10-08 16-11-50](https://user-images.githubusercontent.com/883406/95417566-199bbc80-0981-11eb-9566-1c71db4acd91.png)

**Comment by blmhemu** [comment]
I think it would be better to put it under `gotk bootstrap` command

**Comment by nanikjava** [comment]
@blmhemu The current ARM information is under https://toolkit.fluxcd.io/guides/installation/#bootstrap but from this issue header the requirement is to add the same content under `get started` section ?

@hiddeco can you confirm  what is the exact changed that is required. Happy to take this on as I'm familiar with mkdocs.

**Comment by hiddeco** [comment]
@nanikjava it should look like the following:

![Screenshot from 2020-10-12 11-52-43](https://user-images.githubusercontent.com/10063039/95732767-7f3dc080-0c81-11eb-9c83-6d6d73a07613.png)
![Screenshot from 2020-10-12 11-52-57](https://user-images.githubusercontent.com/10063039/95732774-806eed80-0c81-11eb-87da-eef76ab25c19.png)

**Comment by nanikjava** [comment]
@hiddeco PR submitted. Thanks.

**Comment by stefanprodan** [comment]
Fixed in #327
