### ISSUE TITLE
Create custom flags for options with validation rules

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/toolkit#308]
We have [a couple of flags in the GitOps Toolkit](https://github.com/fluxcd/toolkit/blob/6cce0a39011fc6878981a9c5c57092486c18ba1c/cmd/gotk/main.go#L113-L118) (there may be more) that have complex validation rules.

To describe the available options in the help menus, ensure we are consistent in our validation (messages), and make them more reusable, we should turn these into custom flags [as we did for the SSH key flags](https://github.com/fluxcd/toolkit/blob/main/cmd/gotk/flags.go).

**Comment by rimaddo** [comment]
I would be interested to try this. Just to clarify that I understand correctly, you want to have and equivalent method to `Description` on `PublicKeyAlgorithm` for the other flags and then presumably you would call that [like you're doing here in the init](https://github.com/fluxcd/toolkit/blob/6cce0a39011fc6878981a9c5c57092486c18ba1c/cmd/gotk/create_source_git.go#L105)? Thanks!

**Comment by hiddeco** [comment]
@rimaddo thanks for your interest! :kiwi_fruit: 

The highlighted lines in the first link are all tied to certain flags used within the commands. To de-duplicate this logic, we want a flag for every validation option.

One example:

```go
var supportedArchs = []string{"amd64", "arm", "arm64"}

type Arch string

func (a *Arch) String() string {
	return string(*a)
}

func (a *Arch) Set(str string) error {
	if strings.TrimSpace(str) == "" {
		return fmt.Errorf("no arch given, must be one of: %s",
			strings.Join(supportedArch, ", "))
	}
	for _, v := range supportedArchs {
		if str == v {
			*a = Arch(str)
			return nil
		}
	}
	return fmt.Errorf("unsupported arch '%s', must be one of: %s",
		str, strings.Join(supportedArchs, ", "))
}

func (a *Arch) Type() string {
	return "arch"
}

func (a *Arch) Description() string {
	return fmt.Sprintf("cluster architecture (%s)", strings.Join(supportedArchs, ", "))
}
```

You can than make the following change to initialize the default:

https://github.com/fluxcd/toolkit/blob/5efa1ebe88e1a4271e58293bf9f0a976e5ae4d93/cmd/gotk/install.go#L65

```go
	installArch               Arch = "string"
```

Plus (as you mentioned), register the new custom flag type in the command's `init` (including the nice description):

https://github.com/fluxcd/toolkit/blob/5efa1ebe88e1a4271e58293bf9f0a976e5ae4d93/cmd/gotk/install.go#L86-L87

```go
	installCmd.Flags().Var(&installArch, "arch", installArch.Description())
```

Please note that some of the string slices are used in multiple commands, and thus need to be replaced in multiple files (the above also exist in `bootstrap.go` for example).

Happy hacking :jack_o_lantern::sparkles:

**Comment by StupidScience** [comment]
Since no movement here can I take this one?
@hiddeco WDYT if I'll move all of those flags to internal packages?
Also looks like there is some utils that I can reuse, so may be it is a good idea to move them out in same manner?

**Comment by StupidScience** [comment]
I've sent WIP PR to check if you're ok with this approach.
