### ISSUE TITLE
gotk get sources bucket command not working

### ISSUE THREAD

**Issue by RiskyAdventure** [fluxcd/toolkit#316]
Hello all! After deploying a Bucket object using the CRD, I wanted to see the status of the S3 pull. I found the gotk get sources bucket command at https://toolkit.fluxcd.io/cmd/gotk_get_sources_bucket/ I get an error that only the git and helm options are available... 

❯ gotk get sources bucket                                                                                                                               ─╯
The get source sub-commands print the statuses of the sources.

Usage:
  gotk get sources [command]

Available Commands:
  git         Get GitRepository source statuses
  helm        Get HelmRepository source statuses

**Comment by stefanprodan** [comment]
I think you are using an older version.

```
$ gotk -v
gotk version 0.1.5

$ gotk get sources -h
The get source sub-commands print the statuses of the sources.

Usage:
  gotk get sources [command]

Available Commands:
  bucket      Get Bucket source statuses
  git         Get GitRepository source statuses
  helm        Get HelmRepository source statuses
```

**Comment by RiskyAdventure** [comment]
indeed I am! sorry for the false alarm, thanks for the help.
