### ISSUE TITLE
Upgrade path issue for alpha users

### ISSUE THREAD

**Issue by SpectralHiss** [fluxcd/toolkit#330]
Hello

I am trying to upgrade a slightly old alpha version (pre 0.1 unsure exactly), I am getting api errors with all gotk commands (v1alpha1 vs v1beta1) eg suspend:
```
gotk suspend kustomization oracle-dev
✗ no matches for kind "Kustomization" in version "kustomize.toolkit.fluxcd.io/v1beta1"
```

when i try to bootstrap again using a later tag (eg 0.1.15):
```
Resource: "apiextensions.k8s.io/v1, Resource=customresourcedefinitions", GroupVersionKind: "apiextensions.k8s.io/v1, Kind=CustomResourceDefinition"
Name: "receivers.notification.toolkit.fluxcd.io", Namespace: ""
for: "/tmp/gotk-system364635352/gitops/configs/dev-cluster/gotk-system/toolkit-components.yaml": CustomResourceDefinition.apiextensions.k8s.io "receivers.notification.toolkit.fluxcd.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
✗ install failed
```
My guess is the existing customresource definitions rejecting the update.

Which means I don't think it's possible to just use `bootstrap` to upgrade .  i wouldn't mind nuking the resources and starting again if i could somehow manually de-automate.

Although it's alpha and expected  it would still be nice to supply an FAQ or a section somewhere around upgrade process and the ability to manually deautomate deployments in case of trouble. I hope the upgrade path to v1beta to v1 will be smoother

Thanks for all your work!

**Comment by stefanprodan** [comment]
Assuming you've installed the toolkit in `gitops-system`, you could uninstall it without removing the deployed workloads:

* delete the controllers
```
kubectl -n gitops-system delete deployments --all
```
* remove the finalizers for each kind (kustomization, gitrepositry, helmrelease, helmrepository):
```
kubectl -n gitops-system patch kustomization <name> -p '{"metadata":{"finalizers":null}}
```
* delete the namespace
```
kubectl delete ns gitops-system
```

* delete the crds
```
kubectl delete $(kubectl get crds -oname | grep "toolkit.fluxcd.io")
```

With the latest CLI you should be able to reinstall it, please let me know if this works.

Thanks @SpectralHiss for tying the alpha 🥇 Going forward we will provide a conversion mechanism for CRDs.

**Comment by SpectralHiss** [comment]
Hey thanks so much for your quick response

I am in the process of deleting this (I actually used an old (v0.0.28) binary before i saw your post) it got stuck on delete namespace (status Terminating..),  i think it's because of these finalisers still being there , i cleared them and it worked great. (and my pods are still here

going to run the reinstall slightly later and update

**Comment by stefanprodan** [comment]
I've updated the upgrade guid here https://github.com/fluxcd/toolkit/discussions/288

**Comment by SpectralHiss** [comment]
Thank you so much !! this worked great (there's a small new issue to do with gitlab.com bootstrap but this issue is solved) :+1: :tada:
