### ISSUE TITLE
gitlab.com Bootstrap issue

### ISSUE THREAD

**Issue by SpectralHiss** [fluxcd/toolkit#335]
When starting a fresh install of gitops toolkit, it's managing to do most steps except that it doesn't succesfully add the deploy key ,

on bootstrap:
`gotk bootstrap gitlab --owner acresoftware/terraform --repository k8s-config --branch develop --path gitops/configs/dev-cluster \
--components=source-controller,kustomize-controller,helm-controller,notification-controller --version v0.1.5`
```
► connecting to gitlab.com
✔ repository cloned
✚ generating manifests
✔ components manifests pushed
► installing components in gotk-system namespace
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
namespace/gotk-system configured
networkpolicy.networking.k8s.io/deny-ingress created
role.rbac.authorization.k8s.io/crd-controller-gotk-system created
rolebinding.rbac.authorization.k8s.io/crd-controller-gotk-system created
clusterrolebinding.rbac.authorization.k8s.io/cluster-reconciler-gotk-system created
customresourcedefinition.apiextensions.k8s.io/buckets.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/gitrepositories.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/helmcharts.source.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/helmrepositories.source.toolkit.fluxcd.io configured
service/source-controller created
deployment.apps/source-controller created
customresourcedefinition.apiextensions.k8s.io/kustomizations.kustomize.toolkit.fluxcd.io configured
deployment.apps/kustomize-controller created
customresourcedefinition.apiextensions.k8s.io/helmreleases.helm.toolkit.fluxcd.io configured
deployment.apps/helm-controller created
customresourcedefinition.apiextensions.k8s.io/alerts.notification.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/providers.notification.toolkit.fluxcd.io configured
customresourcedefinition.apiextensions.k8s.io/receivers.notification.toolkit.fluxcd.io configured
service/notification-controller created
service/webhook-receiver created
deployment.apps/notification-controller created
Waiting for deployment "source-controller" rollout to finish: 0 of 1 updated replicas are available...
deployment "source-controller" successfully rolled out
deployment "kustomize-controller" successfully rolled out
deployment "helm-controller" successfully rolled out
deployment "notification-controller" successfully rolled out
✔ install completed
► configuring deploy key
✗ failed to list deploy keys, error: GET https://gitlab.com/api/v4/projects/20733394/deploy_keys: 403 {message: 403 Forbidden}
```

I have seen this before as well on alpha version and had just got the key from the secret and added it manually.. any idea what's happening here?
I have put all permissions on the Personal Access Token, could it have to do with group permissions?

**Comment by SpectralHiss** [comment]
Looks like it's linked to this https://gitlab.com/gitlab-org/gitlab-foss/-/issues/23807

**Comment by SpectralHiss** [comment]
Actually this looks like it's not possible at all in gitlab.com (using the cloud version) https://forum.gitlab.com/t/deploy-keys-api-needs-admin-access/34814/4 i think this is a genuine bootstrapping issue with gitlab.com then..

**Comment by SpectralHiss** [comment]
workaround is to manually add deploy key assuming that the script above has done most setup steps , this leaves flux in a semi-usable state with gitops-system Gitrepository is not syncing but your deployments are..

**Comment by stefanprodan** [comment]
Is ` acresoftware/terraform` a GitLab group? I tested this on my personal account and didn't run into this issue.

**Comment by SpectralHiss** [comment]
Yes it's a group

**Comment by stefanprodan** [comment]
Hmm if GitHub doesn't allow deploy key listing then I guess we should drop GitLab support from gotk bootstrap.

**Comment by stefanprodan** [comment]
@yiannistri @foot @dinosk can you confirm that the GitLab deploy key API is broken?

**Comment by stefanprodan** [comment]
@SpectralHiss for GitLab you could setup gotk like so:

* Install the toolkit controllers:
```sh
gotk install
```
* Add the GitLab repo:
```sh
gotk create source git gotk-system \
--url=ssh://git@gitlab.com/<group>/<repo> \
--branch=develop \
--interval=1m
```
The above command will prompt you to add the deploy key manually.
* Create a kustomization:
```sh
gotk create kustomization gotk-system \
--source=GitRepository/gotk-system \
--path=./gitops/configs/dev-cluster \
--validation=client \
--prune=true \
--interval=10m
```

Before using the above, you should delete the gotk-system dir from `./gitops/configs/dev-cluster` in your git repo.

**Comment by dinosk** [comment]
> @yiannistri @foot @dinosk can you confirm that the GitLab deploy key API is broken?

I think listing deploy keys on gitlab.com indeed requires admin access on the `/deploy_keys` endpoint, but not for listing the deploy keys of a specific project using `/project/{project}/deploy_keys`. Searching for the error in the `fluxcd` org, returns this line which should be ok. https://github.com/fluxcd/pkg/blob/340835442bb3bfb49e53c58b7ef7382e9aa95e8e/git/provider_gitlab.go#L126.

**Comment by stefanprodan** [comment]
@dinosk I'm confused, what needs to change in `fluxcd/pkg/git` to make this work?

**Comment by dinosk** [comment]
@stefanprodan sorry for the confusion, I think it works as is from my tests. Tested 3 cases (personal project, group project, subgroup project) using `gotk version 0.1.6` on `gitlab.com` and an access token with the `api` scope.

```
Personal project case: 

➜  weaveworks git:(master) ✗ ./gotk bootstrap gitlab --owner dinosk --repository gitlab-project --branch master --path . \ --components=source-controller,kustomize-controller,helm-controller,notification-controller --version v0.1.5
► connecting to gitlab.com
✔ repository cloned
✚ generating manifests
✔ components are up to date
► installing components in gotk-system namespace
...
✔ install completed
► configuring deploy key
✔ deploy key configured
► generating sync manifests
► applying sync manifests
◎ waiting for cluster sync
✔ bootstrap finished

Group project case: 

➜  weaveworks git:(master) ✗ ./gotk bootstrap gitlab --owner ggpgroup --repository gitlab-project --branch master --path . \ --components=source-controller,kustomize-controller,helm-controller,notification-controller --version v0.1.5
► connecting to gitlab.com
✔ repository cloned
✚ generating manifests
✔ components manifests pushed
► installing components in gotk-system namespace
...
✔ install completed
► configuring deploy key
✔ deploy key configured
► generating sync manifests
✔ sync manifests pushed
► applying sync manifests
◎ waiting for cluster sync
✔ bootstrap finished

Subgroup project case: 

➜  weaveworks git:(master) ✗ ./gotk bootstrap gitlab --owner ggpgroup/ggpsub --repository gitlab-project --branch master --path . \ --components=source-controller,kustomize-controller,helm-controller,notification-controller --version v0.1.5
► connecting to gitlab.com
✔ repository cloned
✚ generating manifests
✔ components manifests pushed
► installing components in gotk-system namespace
...
✔ install completed
► configuring deploy key
✔ deploy key configured
► generating sync manifests
✔ sync manifests pushed
► applying sync manifests
◎ waiting for cluster sync
✔ bootstrap finished
```

@SpectralHiss if `acresoftware/terraform` is a group/subgroup could it be related to permissions on the `terraform` subgroup maybe?

**Comment by SpectralHiss** [comment]
I am owner on acresoftware, on acresoftware/terraform and on k8s-config also:
:thinking: 
anything else you want me to check?

**Comment by dinosk** [comment]
It is strange that it returned 403, when I attempted with a token with not enough permissions it returned a 401 Unauthorized :thinking:.
Is it the same result @SpectralHiss if you try listing the deploy keys with `curl`?

```
curl --request GET --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" --header "Content-Type: application/json" "https://gitlab.com/api/v4/projects/20733394/deploy_keys"
```

**Comment by SpectralHiss** [comment]
This is what i get:
```
curl --request GET --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" --header "Content-Type: application/json" "https://gitlab.com/api/v4/projects/20733394/deploy_keys"
{"message":"403 Forbidden"}
```

If i try with another token without api I get 403 with:
```
{"error":"insufficient_scope","error_description":"The request requires higher privileges than provided by the access token.","scope":"api read_api"}pi/v4/projects/20733394/deploy_keys" 
```

**Comment by alisondy** [comment]
Hi @SpectralHiss 

I'm not sure this will help but these were the settings that I've used for the token and succesfully bootstrapped with 

@stefanprodan I can update the docs to specify it has to be a personal token, if you are happy with that

![Screen Shot 2020-10-14 at 11 25 19](https://user-images.githubusercontent.com/19580905/96256038-d4464300-0faf-11eb-893a-895bfbc5aaaa.png)

**Comment by stefanprodan** [comment]
@alisondy that would be great, thank you!

**Comment by stefanprodan** [comment]
@SpectralHiss can you please test #351 using the HTTPS auth and let me know if it works for you? Thanks

**Comment by SpectralHiss** [comment]
Sorry for the delay but yes this worked fine! thanks a lot for the prompt fix, gotk is an amazing tool!
