### ISSUE TITLE
gotk uninstall fails for installations with cherry-picked components

### ISSUE THREAD

**Issue by wingsofovnia** [fluxcd/toolkit#359]
## Problem
`gotk uninstall` cmd assumes all toolkit components are installed.

Where: [here](https://github.com/fluxcd/toolkit/blob/4eaf72fa3e017ad5b5d1c405692838996e1c2da1/cmd/gotk/uninstall.go#L101)

## Preconditions
```
gotk install  --components=source-controller,helm-controller --version=latest
```

## Actual behaviour
```
gotk uninstall --crds
Are you sure you want to delete the gotk-system namespace: y
► uninstalling custom resources
error: the server doesn't have a resource type "Kustomization"
```

## Expected behaviour
```
gotk uninstall --crds
Are you sure you want to delete the gotk-system namespace: y
► uninstalling custom resources
No resources found
No resources found
No resources found
No resources found
► uninstalling components
customresourcedefinition.apiextensions.k8s.io "buckets.source.toolkit.fluxcd.io" deleted
customresourcedefinition.apiextensions.k8s.io "gitrepositories.source.toolkit.fluxcd.io" deleted
customresourcedefinition.apiextensions.k8s.io "helmcharts.source.toolkit.fluxcd.io" deleted
customresourcedefinition.apiextensions.k8s.io "helmreleases.helm.toolkit.fluxcd.io" deleted
customresourcedefinition.apiextensions.k8s.io "helmrepositories.source.toolkit.fluxcd.io" deleted
clusterrolebinding.rbac.authorization.k8s.io "cluster-reconciler-gotk-system" deleted
namespace "gotk-system" deleted
✔ uninstall finished
```

## Workaround
Install the expecting component that is missing:
```
gotk install  --components=kustomize-controller --version=latest
```

**Comment by rumsrami** [comment]
I am currently still facing the same problem, and this is the output from the command line
`
$ flux uninstall --resources --crds --namespace=flux-system
Are you sure you want to delete the flux-system namespace: y█
► uninstalling custom resources
error: the server doesn't have a resource type "GitRepository"
✗ kubectl: exit status 1
error: the server doesn't have a resource type "HelmRepository"
✗ kubectl: exit status 1
error: the server doesn't have a resource type "Bucket"
✗ kubectl: exit status 1
kustomization.kustomize.toolkit.fluxcd.io "flux-system" deleted

`
