### ISSUE TITLE
Automate components updates 

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/toolkit#36]
Create GitHub actions workflow that opens PRs every time a controller is released. The PR should bump the version in `manifests/bases` and `go.mod`.

Workflow:
- fetch latest release from GitHub API
- run `go mod edit -require=github.com/fluxcd/source-controller@<VERSION>`
- run `go mod tidy`
- check for changes with `git diff`
- replace the version in `bases/source-controller/kustomization.yaml`
- commit changes
- open PR with `peter-evans/create-pull-request@v2`

**Comment by hiddeco** [comment]
This has been implemented in #177 (and some sequential PRs to improve the base that was added there).
