### ISSUE TITLE
Kustomization Fails when base is an SSH URL

### ISSUE THREAD

**Issue by nniehoff** [fluxcd/toolkit#379]
My kustomization.yaml includes:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: customerx
bases:
  - ../bases
  - git::ssh://git@github.com/example/repo.git?sshkey={base64 id_rsa}
```

Pointing at a private repo on github with an sshkey embedded in the URL.  Kustomize locally successfully builds the correct yaml and can pull from github using the private key but when deploying with the toolkit the customization fails with:

```
kustomize build failed: accumulating resources: accumulateFile "accumulating resources from 'git::ssh://git@github.com/example/repo.git?sshkey={base64 id_rsa}': open /tmp/path/git::ssh:/git@github.com/example/repo.git?sshkey={base64 id_rsa}: no such file or directory", loader.New "trouble cloning git repo ssh://git@github.com/example/repo.git in /tmp/kustomize-436177202: exit status 128"
```

**Comment by hiddeco** [comment]
Remote bases are not supported at the moment, see: https://github.com/fluxcd/kustomize-controller/issues/136, #374 and #326

**Comment by nniehoff** [comment]
@hiddeco Thanks for the quick response
