### ISSUE TITLE
Should tk use KUBECONFIG environmental variable if set?

### ISSUE THREAD

**Issue by paulcarlton-ww** [fluxcd/toolkit#57]
Running tk check I was surprised to see it report an unexpected kubernetes server version.
On investigation it seems that tk supports the specification of a kubeconfig file using --kubeconfig option but if this is not provided it uses ~/.kube/config. 
If a user has set the KUBECONFIG environmental variable they might reasonably expect tk to use that value?

**Comment by stefanprodan** [comment]
tk uses the current kubectl context as it's meant to be run as a kubectl plugin. I think we can overrride it if KUBECONFIG is set.
