### ISSUE TITLE
Use Kubernetes finalizers for garbage collection

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/toolkit#89]
The toolkit controllers should register and trigger [pre-delete hooks](https://book.kubebuilder.io/reference/using-finalizers.html) in their `reconcile` functions to perform garbage collection:

- [x] source-controller
- [x] kustomize-controller
- [x] helm-controller

**Comment by hiddeco** [comment]
To give the above bit more context: we are currently (ab)using predicates for garbage collection, which is an anti-pattern given the fact that they should only be used to filter events before they are handed over to a reconciler.

An added bonus of using finalizers is that we are able to broadcast alerts and/or events for delete operations.
