### ISSUE TITLE
Make tk install write progress report lines to standard error

### ISSUE THREAD

**Issue by paulcarlton-ww** [fluxcd/toolkit#98]
I am using tk install with dry-run and verbose options to generate the yaml to deploy gitops.
However I have to manually edit out the progress report lines emitted by tk install.
If these lines were written to standard error and the yaml lines written to standard out I wouldn't have to remove them manually.

**Comment by stefanprodan** [comment]
Writing to stderr info messages is not a good option, I'll add an `--export` option for this.
